PATH_SEPARATOR = "/"
YEAR_TO_DATE_DASH_FORMAT = "%Y-%m-%d"
SMALL_YEAR_TO_DATE_SLASH_FORMAT = "%y/%m/%d"
SUBSCRIPTION_KEY_NAME = 'subscription'
TO_SUBSCRIBE_OBJ_NAME = 'to_subscribe.csv'

# DDB table names
USER_TABLE_NAME = 'nearby_user'
NEIGHBORHOOD_TABLE_NAME = 'nearby_neighborhood'

# DDB attributes
USER_LAT_ATTR = "LAT"
USER_LNG_ATTR = "LNG"
USER_EMAIL_ATTR = "EMAIL_ID"
USER_STATUS_ATTR = "NEARBY_STATUS"
USER_CREATION_DAY_ATTR = 'CREATION_DAY'

NEIGHBORHOOD_SUBSCRIPTION_ARN_ATTR = 'subscription_arn'
NEIGHBORHOOD_ID_ATTR = 'id'
NEIGHBORHOOD_LAT_ATTR = 'lat'
NEIGHBORHOOD_LNG_ATTR = 'lng'

# pk
USER_TABLE_PK = USER_EMAIL_ATTR
NEIGHBORHOOD_TABLE_PK = NEIGHBORHOOD_ID_ATTR

# gsi
USER_TABLE_STATUS_GSI = "NEARBY_STATUS-index"
USER_TABLE_STATUS_GSI_PK = USER_STATUS_ATTR

# projections
USER_EXTRACTION_DATA_PROJECTION = USER_EMAIL_ATTR + "," + USER_LAT_ATTR + "," + USER_LNG_ATTR

# event types
NEIGHBORHOOD_EVENT_TYPE = 'neighborhood'
USER_EVENT_TYPE = 'user'

# ddb expressions
UPDATE_STATUS_ATTR_EXPRESSION = "set NEARBY_STATUS = :status, NEIGHBORHOOD = :neighborhood_id"
NEARBY_STATUS_SUBSCRIBED = "SUBSCRIBED"
NEARBY_STATUS_TO_SUBSCRIBE = "TO_SUBSCRIBE"

# cloudwatch metrics
SUBSCRIBED_METRIC_NAME = 'SUBSCRIPTION'
ALERT_NEIGHBORHOOD_METRIC = 'ALERT_NEIGHBORHOOD'
